### ISSUE TITLE
Execution failed with JDK 8

### ISSUE THREAD

**Issue by azingel** [jacobono/gradle-wsdl-plugin#6]
I've got an execution failed with JDK 8 (u20 and u40 tested) but it works fine with JDK 7 (on Windows 7).

> java.lang.AssertionError: org.xml.sax.SAXParseException; systemId: jar:file:/C:/Users/devuser/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-xjc/2.2.7-b41/ecd86f12f58c589df43842037f63eea816a2eb63/jaxb-xjc-2.2.7-b41.jar!
/com/sun/tools/xjc/reader/xmlschema/bindinfo/binding.xsd; lineNumber: 52; columnNumber: 88; schema_reference: Failed to read schema document 'xjc.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property.
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:92)
        at org.gradle.jacobo.plugins.ant.AntWsImport.execute(AntWsImport.groovy:60)
        at org.gradle.jacobo.plugins.task.WsdlWsImport.start(WsdlWsImport.groovy:62)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)

**Comment by aram535** [comment]
Before the wsdl block use: 

```
 /*
 *  This allows access to wsdl files on the local machine
 */
System.setProperty('javax.xml.accessExternalSchema', 'file')
```
